Fix upload error in demo file: materials-demo
Repo file: 'materials-demo.cs' from sansar-script repo

Fixes error on upload: error CS1503: Argument 1: cannot convert from 'Sansar.Color' to 'string' in line 187:

Change from:
if (!Sansar.Color.TryParse(Color, out p.Tint))

To:
if (!Sansar.Color.TryParse(tint.ToRGBA(), out p.Tint))

Took me some time to figure out the correct syntax. Test result: Upload successful and functionality correct.


Speculative reservations: As the debug log iterates through all object materials. Only changes to one material are observed. But i guess, as the file is a demo, that is the intention.